version: '3'

services:
  TelemetryApp.Api:
    image: telemetryappapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:6651
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificate/https/certificate.pfx
      - ASPNETCORE_KESTREL__Certificates__Default__Password=aspnet
    build:
      dockerfile: DockerfileApi
    ports:
      - "6651:6651"
  
  TelemetryApp.DockerMonitoring.TelegramBot:
    image: telemetryappdockermonitoringtelegrambot
    build:
      dockerfile: DockerfileDockerMonitoringTelegramBot

networks:
  default:
    name: TelemetryAppNetwork
