apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-telegrambot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetrytelegrambot
  template:
    metadata:
      labels:
        app: telemetrytelegrambot
    spec:
      containers:
        - name: telemetrytelegrambot
          image: localhost:5000/telemetrytelegrambot:{{TAG_NUMBER}}