apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetryapi
  template:
    metadata:
      labels:
        app: telemetryapi
    spec:
      containers:
        - name: telemetryapi
          image: localhost:5000/telemetryapi:{{TAG_NUMBER}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /certificate/https/certificate.pfx
            - name: ASPNETCORE_KESTREL__Certificates__Default__Password
              value: aspnet
            - name: ASPNETCORE_URLS
              value: https://+:6651
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-api-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: telemetryapi
  ports:
    - name: telemetryapi
      protocol: TCP
      port: 6651
      targetPort: 6651
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-api-nodeport-service
spec:
  type: NodePort
  selector:
    app: telemetryapi
  ports:
    - name: telemetryapi
      protocol: TCP
      port: 6651
      targetPort: 6651
      nodePort: 30200